---
kind: pipeline
type: docker
name: default

steps:
  - name: source
    image: alpine:3.11
    commands:
      - apk add --update --no-cache curl git jq
      - LATEST=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r ".tag_name")
      - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/hugo/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
      - git clone -b $LATEST https://github.com/gohugoio/hugo.git
      - echo -n "$LATEST,latest" > .tags

  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/hugo
      context: hugo
      dockerfile: hugo/Dockerfile
      build_args:
        - HUGO_BUILD_TAGS=extended
      when:
        event:
          - cron
        cron:
          - nightly
---
kind: signature
hmac: de435705328504007263cda7770a1fd83a88c71cc928203984f455e836271147

...
